# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8157de19e1f530a764e2a72b10d65b60354d438d08be3e7df59bd40a4137e4d0443e2526dda1b0400245c2fe7717f287cfb83150dd207a83ffb1dd3c11d0056

test:
  secret_key_base: d279449179d6fd50f145dde65e0028f373826c101a2644bfbd42051cac0a655b8363da68b67e088cf7eacd4b2adcd447d2bcccd24ef79f9bbf57df3b9259a3b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
